# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-07 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('citizens', models.IntegerField(default=0)),
                ('allowed', models.IntegerField(default=0)),
                ('voting_cards', models.IntegerField(default=0)),
                ('votes', models.IntegerField(default=0)),
                ('valid_votes', models.IntegerField(default=0)),
                ('votes_for_cand_1', models.IntegerField(default=0)),
                ('votes_for_cand_2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Voivodeship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('citizens', models.IntegerField()),
                ('allowed', models.IntegerField()),
                ('voting_cards', models.IntegerField()),
                ('votes', models.IntegerField()),
                ('valid_votes', models.IntegerField()),
                ('votes_for_cand_1', models.IntegerField(default=0)),
                ('votes_for_cand_2', models.IntegerField(default=0)),
                ('iso_code', models.CharField(choices=[('PL-DS', 'dolno\u015bl\u0105skie'), ('PL-KP', 'kujawsko-pomorskie'), ('PL-LU', 'lubelskie'), ('PL-LB', 'lubuskie'), ('PL-LD', '\u0142\xf3dzkie'), ('PL-MA', 'ma\u0142opolskie'), ('PL-MZ', 'mazowieckie'), ('PL-OP', 'opolskie'), ('PL-PK', 'podkarpackie'), ('PL-PD', 'podlaskie'), ('PL-PM', 'pomorskie'), ('PL-SL', '\u015bl\u0105skie'), ('PL-SK', '\u015bwi\u0119tokrzystkie'), ('PL-WN', 'warmi\u0144sko-mazurskie'), ('PL-WP', 'wielkopolskie'), ('PL-ZP', 'zachodniopomorskie')], default='PL-MZ', max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='voivodeship_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='elections.Voivodeship'),
        ),
    ]
