# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-07 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_community_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voivodeship',
            old_name='iso_code',
            new_name='voi_choice',
        ),
        migrations.RemoveField(
            model_name='community',
            name='id',
        ),
        migrations.AlterField(
            model_name='community',
            name='kind',
            field=models.CharField(choices=[('1', 'miasto'), ('2', 'wie\u015b'), ('3', 'statki'), ('4', 'zagranica')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
