# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-07 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_auto_20160507_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='voivodeship_ptr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Voivodeship'),
        ),
    ]
