# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-11 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_auto_20160507_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_cards', models.IntegerField(default=0)),
                ('votes', models.IntegerField(default=0)),
                ('valid_votes', models.IntegerField(default=0)),
                ('votes_for_cand_1', models.IntegerField(default=0)),
                ('votes_for_cand_2', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='community',
            name='valid_votes',
        ),
        migrations.RemoveField(
            model_name='community',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='community',
            name='votes_for_cand_1',
        ),
        migrations.RemoveField(
            model_name='community',
            name='votes_for_cand_2',
        ),
        migrations.RemoveField(
            model_name='community',
            name='voting_cards',
        ),
        migrations.AddField(
            model_name='vote',
            name='community_ptr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Community'),
        ),
    ]
