# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-20 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_auto_20160511_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='last_modification',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
