# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-29 12:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0008_auto_20160622_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='last_modification',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
