# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-30 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0010_auto_20160830_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='last_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
