# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-05 09:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0014_remove_vote_last_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='last_modification',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 5, 9, 41, 29, 124793, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
